default: &default
 adapter: mysql2
 encoding: utf8
 pool: <%=ENV.fetch("RAILS_MAX_THREADS") { 5 }%>
 timeout: 5000

development:
 <<: *default
 database: development_db
 username: <%=ENV["DATEBASE_USER_NAME"]%>
 password: <%=ENV["DATEBASE_USER_PASS"]%>
 host: localhost
 #host: db

test:
 <<: *default
 database: test_db
 username: root
 password: root
 #username: <%= ENV['DATEBASE_USER_NAME']%>
 #password: <%= ENV['DATEBASE_USER_PASS']%>
 host: 127.0.0.1

production:
 <<: *default
 database: <%=ENV["DB_NAME"]%> 
 username: <%=ENV["DB_USERNAME"]%>
 password: <%=ENV["DB_PASSWORD"]%>